name: led_digital_scroll
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / Icons
  cupertino_icons: ^1.0.8

  # Text-to-speech (optional)
  flutter_tts: ^4.0.0

  # Networking
  http: ^1.5.0

  # Color picker UI
  flutter_colorpicker: ^1.0.3

  # Share files (images/gifs)
  share_plus: ^12.0.0
  url_launcher: ^6.1.10
  webview_flutter: ^4.10.2
  speech_to_text: ^7.3.0
  image: ^4.0.17
  shared_preferences: ^2.1.2
  marquee: ^2.2.3
  image_picker: ^1.2.0
  path_provider: ^2.0.14
  file_selector: ^1.0.4
  audioplayers: ^6.5.1
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/

    # - assets/images/whats.png
    # - assets/images/insta.png
    # - assets/images/face.png
    # - assets/images/message.png
    # - assets/images/snapchat.png
    # - assets/images/telig.png
    # - assets/images/email.png
    # - assets/images/camera.png
    # - assets/images/ai.png
    # - assets/images/brow.png
    # - assets/images/micro.png
