name: led_digital_scroll
description: LED Digital Scroller with Video Recording
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Video & FFmpeg
  ffmpeg_kit_flutter_new: ^3.2.0 # Use the new fork

  # File handling & sharing
  gallery_saver_plus: ^3.2.9
  share_plus: ^7.0.1
  cross_file: ^0.3.3
  file_selector: ^0.9.3
  path_provider: ^2.1.0
  path: ^1.9.0
  device_info_plus: ^10.1.0

  # Audio
  audioplayers: ^6.5.1
  just_audio: ^0.9.35

  # Images
  image_picker: ^1.0.4
  image: ^4.0.17

  # UI & Utilities
  provider: ^6.0.5
  url_launcher: ^6.2.1
  permission_handler: ^11.1.0
  marquee: ^2.3.0
  flutter_tts: ^4.0.2
  speech_to_text: ^7.3.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
